[profile.default]
src = "validator-registry"
out = "artifacts"
libs = ["node_modules"]

[fmt]
int_types = "long"
line_length = 120
tab_width = 4
bracket_spacing = true
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
